packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  react19:
    react: ^19.0.0-rc-66855b96-20241106
    react-dom: ^19.0.0-rc-66855b96-20241106
    "@types/react": npm:types-react@19.0.0-rc.1
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
